<a href="https://colab.research.google.com/github/MariamKhan98/mariamkhan98/blob/main/tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install keras

In [1]:
import tensorflow as tf



In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                                            tf.keras.layers.Dense(128, activation='relu'),
                                                            tf.keras.layers.Dropout(0.2),
                                                            tf.keras.layers.Dense(10)])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.41092294,  0.10788715,  0.27581528, -0.22197995, -0.45372027,
         0.08928911, -0.20128706,  0.36820632, -0.00892182, -0.00901739]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.14076622, 0.10396608, 0.12297645, 0.07475362, 0.05929098,
        0.10205039, 0.0763166 , 0.13487978, 0.09250436, 0.09249552]],
      dtype=float32)

In [11]:
#create a loss function
losses = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
losses(y_train[:1], predictions).numpy()

2.2822886

In [12]:
model.compile(optimizer='adam', loss=losses, metrics=['accuracy'])

In [13]:
model.compile(optimizer='adam', loss=losses, metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8587 - loss: 0.4774
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9539 - loss: 0.1547
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9683 - loss: 0.1061
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9732 - loss: 0.0879
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9767 - loss: 0.0750


In [14]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9772 - loss: 0.0736


[0.07360193878412247, 0.9771999716758728]

In [15]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[1.94532079e-09, 6.90078661e-09, 7.63726632e-07, 3.92137918e-05,
        1.79671486e-11, 8.66778933e-08, 2.02843723e-14, 9.99959350e-01,
        2.09004398e-07, 3.77393036e-07],
       [5.79100927e-08, 5.14170642e-05, 9.99919176e-01, 2.88344927e-05,
        1.60151189e-12, 2.71600300e-07, 3.26301794e-08, 3.87195137e-12,
        2.40053794e-07, 1.20594927e-14],
       [1.29810402e-07, 9.99000251e-01, 1.27727151e-04, 1.04895644e-05,
        1.07798776e-04, 1.66483042e-05, 7.31136461e-05, 4.53055400e-04,
        2.10192011e-04, 5.90472268e-07]], dtype=float32)>